controller:
  funds_controller:
    page: 10
    random_pw: 8
  statements_controller:
    page: 5

statements:
  form:
    up_down: [["Up", 1],["Down", 0]]

registrations:
  edit:
    phone_number_default:  "'alias': '999-999-9999'"

random_key: 1_000_000
views:
  funds:
    form:
      default_money: 0
